```ini
[Rainmeter]
Update=500
AccurateText=1
DynamicWindowSize=1
MiddleMouseDownAction=!Execute [!RefreshApp]

[Metadata]
Name=TRANSSKIN
Author=M.NIKHIL
Version=1.0

[Variables]
@Include=#ROOTCONFIGPATH#\@Settings\Variables.inc


; =========================================================
; MEASURES
; =========================================================


; -------------------------
; Network
; -------------------------

[MeasureIP]
Measure=Plugin
Plugin=WebParser.dll
Url=http://checkip.dyndns.org
UpdateRate=1440
RegExp="(?siU)Address: (.*)</body>"
StringIndex=1
Substitute="":"N/A"

[MeasureNetIn]
Measure=NetIn
NetInSpeed=#maxDownload#

[MeasureNetOut]
Measure=NetOut
NetOutSpeed=#maxUpload#

[MeasureNetInTotal]
Measure=NetIn
Cumulative=1

[MeasureNetOutTotal]
Measure=NetOut
Cumulative=1


; -------------------------
; CPU
; -------------------------

[MeasureCPU]
Measure=CPU
Processor=0
MinValue=0
MaxValue=100

[MeasureCore1]
Measure=CPU
Processor=1
MinValue=0
MaxValue=100

[MeasureCore1Speed]
Measure=Plugin
Plugin=CoreTemp
Processor=1
CoreTempType=CpuSpeed

[MeasureCore2]
Measure=CPU
Processor=2
MinValue=0
MaxValue=100

[MeasureCore3]
Measure=CPU
Processor=3
MinValue=0
MaxValue=100

[MeasureCore4]
Measure=CPU
Processor=4
MinValue=0
MaxValue=100

[MeasureCPUMHz]
Measure=Plugin
Plugin=Plugins\PowerPlugin.dll
PowerState=MHZ
UpdateDivider=3600

[MeasureCPUName]
Measure=Registry
RegHKey=HKEY_LOCAL_MACHINE
RegKey=HARDWARE\DESCRIPTION\System\CentralProcessor\0
RegValue=ProcessorNameSTRING
UpdateDivider=3000


; -------------------------
; RAM
; -------------------------

; Used RAM in bytes
[MeasureRAMUsed]
Measure=PhysicalMemory
UpdateDivider=20

; Total RAM in bytes
[MeasureRAMTotal]
Measure=PhysicalMemory
Total=1
UpdateDivider=20

; RAM percentage
[MeasureRAMPercent]
Measure=Calc
Formula=(MeasureRAMUsed/MeasureRAMTotal)*100
MinValue=0
MaxValue=100
UpdateDivider=20


; -------------------------
; SWAP
; -------------------------

; Used SWAP in bytes
[MeasureSwapUsed]
Measure=SwapMemory
UpdateDivider=20

; Total SWAP in bytes
[MeasureSwapTotal]
Measure=SwapMemory
Total=1
UpdateDivider=20

; SWAP percentage
[MeasureSwapPercent]
Measure=Calc
Formula=(MeasureSwapUsed/MeasureSwapTotal)*100
MinValue=0
MaxValue=100
UpdateDivider=20


; -------------------------
; Processes
; -------------------------

[MeasureTopCPULabel]
Measure=Plugin
Plugin=Plugins\TopProcesses.dll
ReQuery=1
IgnoredProcesses=Idle|_Total|rundll32|wscript|userinit
MetricType=CPU
ProcNums=2-6
Format="%pName"

[MeasureTopCPUMemory]
Measure=Plugin
Plugin=Plugins\TopProcesses.dll
ReQuery=1
IgnoredProcesses=Idle|_Total|rundll32|wscript|userinit
MetricType=CPU
ProcNums=2-6
Format="%Memory"

[MeasureTopCPUPerc]
Measure=Plugin
Plugin=Plugins\TopProcesses.dll
ReQuery=1
IgnoredProcesses=Idle|_Total|rundll32|wscript|userinit
MetricType=CPU
ProcNums=2-6
Format="%CPU%"


; -------------------------
; Disk
; -------------------------

[MeasureTotalDiskC]
Measure=FreeDiskSpace
Drive=C:
Total=1
UpdateDivider=120

[MeasureUsedDiskC]
Measure=FreeDiskSpace
Drive=C:
InvertMeasure=1
UpdateDivider=120

[MeasureTotalDiskD]
Measure=FreeDiskSpace
Drive=D:
Total=1
UpdateDivider=120

[MeasureUsedDiskD]
Measure=FreeDiskSpace
Drive=D:
InvertMeasure=1
UpdateDivider=120


; =========================================================
; METERS
; =========================================================

[Background]
Meter=IMAGE
ImageName=


; =========================================================
; TIME / DATE
; =========================================================

[MeasureDate]
Measure=Time
Format=%A, %B %#d, %Y

[Measure24HrTime]
Measure=Time
Format=%H:%M


[MeterTime]
Meter=STRING
MeasureName=Measure24HrTime
StringAlign=CENTER
FontFace=Open Sans Light
FontSize=36
FontColor=#WHITE#
X=144
Y=10
AntiAlias=1


[MeterDate]
Meter=STRING
MeasureName=MeasureDate
StringAlign=CENTER
FontFace=Open Sans Light
FontSize=14
FontColor=#WHITE#
X=144
Y=68
AntiAlias=1


; =========================================================
; NETWORK
; =========================================================

[UploadTextLabel]
Meter=STRING
StringAlign=LEFT
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=95
Text="Up: "
AntiAlias=1

[DownloadTextLabel]
Meter=STRING
StringAlign=LEFT
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=156
Y=95
Text="Down:"
AntiAlias=1


[SentTextLabel]
Meter=STRING
StringAlign=LEFT
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=175
Text="Sent:"
AntiAlias=1

[RecievedTextLabel]
Meter=STRING
StringAlign=LEFT
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=156
Y=175
Text="Recieved:"
AntiAlias=1


; Network Values

[UploadTextValue]
Meter=STRING
MeasureName=MeasureNetOut
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=34
Y=95
Text=" %1B"
AntiAlias=1
AutoScale=1

[DownloadTextValue]
Meter=STRING
MeasureName=MeasureNetIn
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=200
Y=95
Text="%1B"
AntiAlias=1
AutoScale=1


[SentTextValue]
Meter=STRING
MeasureName=MeasureNetOutTotal
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=42
Y=175
Text="%1B"
AntiAlias=1
AutoScale=1

[RecievedTextValue]
Meter=STRING
MeasureName=MeasureNetInTotal
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=222
Y=175
Text="%1B"
AntiAlias=1
AutoScale=1


; Network Graphs

[UploadUnderline]
Meter=IMAGE
SolidColor=#WHITE#
X=10
Y=164
W=119
H=1

[DownloadUnderline]
Meter=IMAGE
SolidColor=#white#
X=156
Y=164
W=119
H=1


[UploadHistogram]
Meter=Histogram
MeasureName=MeasureNetOut
PrimaryColor=#white#
X=10
Y=120
W=119
H=44

[DownloadHistogram]
Meter=Histogram
MeasureName=MeasureNetIn
PrimaryColor=#white#
X=156
Y=120
W=119
H=44


; =========================================================
; CPU CORES
; =========================================================

[CPU1Label]
Meter=STRING
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=195
Text="CPU 1:"
AntiAlias=1

[CPU2Label]
Meter=STRING
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=R
Text="CPU 2:"
AntiAlias=1

[CPU3Label]
Meter=STRING
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=R
Text="CPU 3:"
AntiAlias=1

[CPU4Label]
Meter=STRING
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=R
Text="CPU 4:"
AntiAlias=1


; CPU Bars

[CPU1Bar]
Meter=Bar
MeasureName=MeasureCore1
BarOrientation=HORIZONTAL
BarColor=#white#
X=100
Y=200
W=100
H=3

[CPU2Bar]
Meter=Bar
MeasureName=MeasureCore2
BarOrientation=HORIZONTAL
BarColor=#white#
X=100
Y=212
W=100
H=3

[CPU3Bar]
Meter=Bar
MeasureName=MeasureCore3
BarOrientation=HORIZONTAL
BarColor=#white#
X=100
Y=224
W=100
H=3

[CPU4Bar]
Meter=Bar
MeasureName=MeasureCore4
BarOrientation=HORIZONTAL
BarColor=#white#
X=100
Y=236
W=100
H=3


; CPU Percentages

[CPU1Value]
Meter=String
MeasureName=MeasureCore1
StringAlign=RIGHT
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=277
Y=195
PostFix=%
AntiAlias=1

[CPU2Value]
Meter=String
MeasureName=MeasureCore2
StringAlign=RIGHT
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=277
Y=R
PostFix=%
AntiAlias=1

[CPU3Value]
Meter=String
MeasureName=MeasureCore3
StringAlign=RIGHT
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=277
Y=R
PostFix=%
AntiAlias=1

[CPU4Value]
Meter=String
MeasureName=MeasureCore4
StringAlign=RIGHT
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=277
Y=R
PostFix=%
AntiAlias=1


; =========================================================
; CPU HISTOGRAM
; =========================================================

[CPUHistogramUnderline]
Meter=IMAGE
SolidColor=#white#
X=20
Y=299
W=265
H=1

[CPUHistogram]
Meter=Histogram
MeasureName=MeasureCPU
PrimaryColor=#white#
SecondaryColor=#WHITE#
X=20
Y=249
W=265
H=50


; =========================================================
; RAM
; =========================================================

[RAMLabel]
Meter=STRING
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=310
Text="RAM:"
AntiAlias=1


[RAMPercent]
Meter=STRING
MeasureName=MeasureRAMPercent
StringAlign=CENTER
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=120
Y=310
Text="%1%"
NumOfDecimals=1
AntiAlias=1


[RAMValue]
Meter=STRING
MeasureName=MeasureRAMUsed
MeasureName2=MeasureRAMTotal
StringAlign=RIGHT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=277
Y=310
Text="%1B / %2B"
NumOfDecimals=1
AutoScale=1
AntiAlias=1


[RAMBar]
Meter=BAR
MeasureName=MeasureRAMPercent
BarOrientation=HORIZONTAL
BarColor=#white#
SolidColor=255,255,255,20
X=10
Y=333
W=265
H=4


; =========================================================
; SWAP
; =========================================================

[SwapLabel]
Meter=STRING
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=345
Text="SWAP:"
AntiAlias=1


[SwapPercent]
Meter=STRING
MeasureName=MeasureSwapPercent
StringAlign=CENTER
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=120
Y=345
Text="%1%"
NumOfDecimals=1
AntiAlias=1


[SwapValue]
Meter=STRING
MeasureName=MeasureSwapUsed
MeasureName2=MeasureSwapTotal
StringAlign=RIGHT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#WHITE#
X=277
Y=345
Text="%1B / %2B"
NumOfDecimals=1
AutoScale=1
AntiAlias=1


[SwapBar]
Meter=BAR
MeasureName=MeasureSwapPercent
BarOrientation=HORIZONTAL
BarColor=#white#
SolidColor=255,255,255,20
X=10
Y=368
W=265
H=4

; =========================================================
; DISK STORAGE
; =========================================================

[CLabel]
Meter=STRING
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=420
Text="C:\"
LeftMouseUpAction=["C:\"]
AntiAlias=1

[C]
Meter=STRING
MeasureName=MeasureUsedDiskC
MeasureName2=MeasureTotalDiskC
StringAlign=RIGHT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=277
Y=420
Text="%1B/%2B used"
NumOfDecimals=1
AutoScale=1
AntiAlias=1

[CBar]
Meter=Bar
MeasureName=MeasureUsedDiskC
BarOrientation=HORIZONTAL
BarColor=#white#
SolidColor=255,255,255,20
X=10
Y=438
W=265
H=4


[DLabel]
Meter=STRING
StringAlign=LEFT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=10
Y=450
Text="D:\"
LeftMouseUpAction=["D:\"]
AntiAlias=1

[D]
Meter=STRING
MeasureName=MeasureUsedDiskD
MeasureName2=MeasureTotalDiskD
StringAlign=RIGHT
StringCase=UPPER
FontFace=Open Sans
FontSize=10
FontColor=#white#
X=277
Y=450
Text="%1B/%2B used"
NumOfDecimals=1
AutoScale=1
AntiAlias=1

[DBar]
Meter=Bar
MeasureName=MeasureUsedDiskD
BarOrientation=HORIZONTAL
BarColor=#white#
SolidColor=255,255,255,20
X=10
Y=468
W=265
H=4
```